apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
  labels:
    name: resultapp-service
    app: votingapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: resultapp-pod
    app: votingapp
    